# Generated by Django 3.1.6 on 2021-03-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mspatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(default='', max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('datecreated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mscase',
            fields=[
                ('formdate', models.DateField()),
                ('studyid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('ms_now', models.CharField(choices=[('RR', 'Relapsing-remitting MS'), ('SP', 'Secondary progressive MS'), ('PP', 'Primary progressive MS'), ('Other', 'Other')], max_length=10)),
                ('conv_to_sp', models.CharField(max_length=20)),
                ('date_diag', models.DateField()),
                ('ms_diag', models.CharField(choices=[('RR', 'Relapsing-remitting MS'), ('SP', 'Secondary progressive MS'), ('PP', 'Primary progressive MS'), ('Other', 'Other')], max_length=10)),
                ('date_onset', models.DateField()),
                ('num_relapses', models.IntegerField()),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=10)),
                ('pastmodtreat', models.CharField(choices=[('Alemtuzumab', 'Alemtuzumab'), ('Avonex', 'Avonex'), ('Betaferon', 'Betaferon'), ('Copaxone', 'Copaxone'), ('Extavia', 'Extavia'), ('Fingolimod', 'Fingolimod'), ('Mitoxantrone', 'Mitoxantrone'), ('Natalizumab', 'Natalizumab'), ('Ocrelizumab', 'Ocrelizumab'), ('Rebif', 'Rebif'), ('Tecfidera', 'Tecfidera'), ('Teriflunomide', 'Teriflunomide'), ('None', 'None')], max_length=20)),
                ('pastmoddatestart', models.DateField()),
                ('pastmodtreatstop', models.DateField()),
                ('pastmodreason', models.CharField(choices=[('Lack of efficacy', 'Lack of efficacy'), ('Side Effects', 'Side Effects'), ('Other', 'Other')], max_length=20)),
                ('presmodtreat', models.CharField(choices=[('Alemtuzumab', 'Alemtuzumab'), ('Avonex', 'Avonex'), ('Betaferon', 'Betaferon'), ('Copaxone', 'Copaxone'), ('Extavia', 'Extavia'), ('Fingolimod', 'Fingolimod'), ('Mitoxantrone', 'Mitoxantrone'), ('Natalizumab', 'Natalizumab'), ('Ocrelizumab', 'Ocrelizumab'), ('Rebif', 'Rebif'), ('Tecfidera', 'Tecfidera'), ('Teriflunomide', 'Teriflunomide'), ('None', 'None')], max_length=20)),
                ('presmoddatestart', models.DateField()),
                ('edssscore', models.IntegerField()),
                ('edssdate', models.DateField()),
                ('walkrangetime', models.TimeField()),
                ('walkrangedist', models.IntegerField()),
                ('walkrangeeval', models.CharField(choices=[('Self-estimated', 'Self-estimated'), ('Trundle wheel', 'Trundle wheel'), ('Treadmill', 'Treadmill')], max_length=20)),
                ('pregnant', models.BooleanField(null=True)),
                ('smoker', models.BooleanField(null=True)),
                ('cigperday', models.IntegerField(null=True)),
                ('smokersince', models.IntegerField(null=True)),
                ('onsetlocal', models.CharField(choices=[('Spinal', 'Spinal'), ('Cortex', 'Cortex'), ('Visual', 'Visual'), ('Cerebellar/brainstem', 'Cerebellar/brainstem')], max_length=30, null=True)),
                ('onsetsympt', models.CharField(choices=[('Vision', 'Vision'), ('Motor', 'Motor'), ('Sensory', 'Sensory'), ('Coordination', 'Coordination'), ('Bowel/Bladder', 'Bowel/Bladder'), ('Fatigue', 'Fatigue'), ('Cognitive', 'Cognitive'), ('Encephalopathy', 'Encephalopathy'), ('Other', 'Other')], max_length=30, null=True)),
                ('personcompleting', models.CharField(blank=True, max_length=30, null=True)),
                ('comorbidities', models.BooleanField(null=True)),
                ('ethnicity', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(null=True)),
                ('race', models.CharField(max_length=20, null=True)),
                ('mspatient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mspatient')),
            ],
        ),
    ]
