# Generated by Django 3.1.6 on 2021-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mspatient',
            name='id',
        ),
        migrations.AlterField(
            model_name='mspatient',
            name='studyid',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
