# Generated by Django 3.1.6 on 2021-03-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210307_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mspatient',
            new_name='Mscase',
        ),
    ]
