# Generated by Django 3.1.6 on 2021-04-20 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210315_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscase',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mscase',
            name='cigperday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mscase',
            name='comorbidities',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mscase',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mscase',
            name='onsetlocal',
            field=models.CharField(blank=True, choices=[('Spinal', 'Spinal'), ('Cortex', 'Cortex'), ('Visual', 'Visual'), ('Cerebellar/brainstem', 'Cerebellar/brainstem')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mscase',
            name='onsetsympt',
            field=models.CharField(blank=True, choices=[('Vision', 'Vision'), ('Motor', 'Motor'), ('Sensory', 'Sensory'), ('Coordination', 'Coordination'), ('Bowel/Bladder', 'Bowel/Bladder'), ('Fatigue', 'Fatigue'), ('Cognitive', 'Cognitive'), ('Encephalopathy', 'Encephalopathy'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mscase',
            name='personcompleting',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mscase',
            name='pregnant',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mscase',
            name='race',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mscase',
            name='smoker',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mscase',
            name='smokersince',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
