# Generated by Django 3.1.6 on 2021-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_doctorapplication_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mscase',
            name='walkrangetime',
            field=models.CharField(max_length=5),
        ),
    ]
