# Generated by Django 3.1.6 on 2021-05-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210424_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscase',
            name='studyid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
